version: "2.12.2"
services:
  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "zhaoxijun7"
      MYSQL_DATABASE: "zhihu"
      MYSQL_PASSWORD: "zhaoxijun7"
    volumes:
      -
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  app:
    build: .
    depends_on:
      - mysql
      - redis